web:
  image: nginx
  volumes:
   - $PWD/vhosts:/etc/nginx/conf.d
   - $PWD/cert:/etc/nginx/cert
  ports:
   - "80:80"
   - "443:443"
  environment:
   - NGINX_HOST=liyuequn.com
   - NGINX_PORT=80
   - NGINX_PORT=443
  restart: always
  command: /bin/bash -c "exec nginx -g 'daemon off;'"