web:
  image: nginx
  volumes:
   - $PWD/vhosts:/etc/nginx/conf.d
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=liyuequn.com
   - NGINX_PORT=80
  command: /bin/bash -c "exec nginx -g 'daemon off;'"